import { useAuthContext } from "./AuthContext";

export const CUSTOMERS_VIEW_PERMISSION = "customers.view";
export const CUSTOMERS_MANAGE_PERMISSION = "customers.manage";
export const CUSTOMERS_HISTORY_PERMISSION = "customers.history";

export const CATALOG_CREATE_PERMISSION = "catalog.create";
export const CATALOG_UPDATE_PERMISSION = "catalog.update";
export const CATALOG_DELETE_PERMISSION = "catalog.delete";
export const ORDER_CREATE_PERMISSION = "orders.create";
export const ORDER_REFUND_PERMISSION = "orders.refund";
export const ORDER_VOID_PERMISSION = "orders.void";
export const CUSTOMER_ORDER_VIEW_PERMISSION = "customer_orders.view";
export const CUSTOMER_ORDER_CREATE_PERMISSION = "customer_orders.create";
export const CUSTOMER_ORDER_UPDATE_PERMISSION = "customer_orders.update";
export const CUSTOMER_ORDER_CANCEL_PERMISSION = "customer_orders.cancel";
export const CUSTOMER_ORDER_CHECKOUT_PERMISSION = "customer_orders.checkout";
export const INVENTORY_ADJUST_PERMISSION = "inventory.adjust";
export const EXPENSES_MANAGE_PERMISSION = "expenses.manage";
export const REPORTS_VIEW_ALL_PERMISSION = "reports.view_all";
export const SHIFT_OPEN_PERMISSION = "shifts.open";
export const SHIFT_CLOSE_PERMISSION = "shifts.close";
export const BILLING_VIEW_PERMISSION = "billing.view";
export const BILLING_MANAGE_PERMISSION = "billing.manage";

const ROLE_PERMISSIONS: Record<string, ReadonlyArray<string>> = {
  owner: [
    CUSTOMERS_VIEW_PERMISSION,
    CUSTOMERS_MANAGE_PERMISSION,
    CUSTOMERS_HISTORY_PERMISSION,
    CATALOG_CREATE_PERMISSION,
    CATALOG_UPDATE_PERMISSION,
    CATALOG_DELETE_PERMISSION,
    ORDER_CREATE_PERMISSION,
    ORDER_REFUND_PERMISSION,
    ORDER_VOID_PERMISSION,
    CUSTOMER_ORDER_VIEW_PERMISSION,
    CUSTOMER_ORDER_CREATE_PERMISSION,
    CUSTOMER_ORDER_UPDATE_PERMISSION,
    CUSTOMER_ORDER_CANCEL_PERMISSION,
    CUSTOMER_ORDER_CHECKOUT_PERMISSION,
    INVENTORY_ADJUST_PERMISSION,
    EXPENSES_MANAGE_PERMISSION,
    REPORTS_VIEW_ALL_PERMISSION,
    SHIFT_OPEN_PERMISSION,
    SHIFT_CLOSE_PERMISSION,
    BILLING_VIEW_PERMISSION,
    BILLING_MANAGE_PERMISSION,
  ],
  manager: [
    CUSTOMERS_VIEW_PERMISSION,
    CUSTOMERS_MANAGE_PERMISSION,
    CUSTOMERS_HISTORY_PERMISSION,
    CATALOG_CREATE_PERMISSION,
    CATALOG_UPDATE_PERMISSION,
    CATALOG_DELETE_PERMISSION,
    ORDER_CREATE_PERMISSION,
    ORDER_REFUND_PERMISSION,
    ORDER_VOID_PERMISSION,
    CUSTOMER_ORDER_VIEW_PERMISSION,
    CUSTOMER_ORDER_CREATE_PERMISSION,
    CUSTOMER_ORDER_UPDATE_PERMISSION,
    CUSTOMER_ORDER_CANCEL_PERMISSION,
    CUSTOMER_ORDER_CHECKOUT_PERMISSION,
    INVENTORY_ADJUST_PERMISSION,
    EXPENSES_MANAGE_PERMISSION,
    REPORTS_VIEW_ALL_PERMISSION,
    SHIFT_OPEN_PERMISSION,
    SHIFT_CLOSE_PERMISSION,
  ],
  cashier: [
    CUSTOMERS_VIEW_PERMISSION,
    ORDER_CREATE_PERMISSION,
    CUSTOMER_ORDER_VIEW_PERMISSION,
    CUSTOMER_ORDER_CREATE_PERMISSION,
    CUSTOMER_ORDER_UPDATE_PERMISSION,
    CUSTOMER_ORDER_CANCEL_PERMISSION,
    CUSTOMER_ORDER_CHECKOUT_PERMISSION,
    SHIFT_OPEN_PERMISSION,
    SHIFT_CLOSE_PERMISSION,
  ],
  staff: [
    CUSTOMERS_VIEW_PERMISSION,
    ORDER_CREATE_PERMISSION,
    CUSTOMER_ORDER_VIEW_PERMISSION,
    CUSTOMER_ORDER_CREATE_PERMISSION,
    CUSTOMER_ORDER_UPDATE_PERMISSION,
    CUSTOMER_ORDER_CANCEL_PERMISSION,
    CUSTOMER_ORDER_CHECKOUT_PERMISSION,
  ],
};

export function permissionsForRole(role: string): Set<string> {
  return new Set(ROLE_PERMISSIONS[role] ?? []);
}

export function usePermission(permission: string): boolean {
  const { state } = useAuthContext();
  if (state.status !== "authenticated") return false;
  return permissionsForRole(state.user.role).has(permission);
}
